export enum Routes {
  trainers = "/dashboard/trainers",
  "create-trainer" = "/dashboard/trainers/create",
  "add-trainer" = "/dashboard/trainers/add",
  schedule = "/dashboard/schedule",
  "add-class" = "/dashboard/schedule/add-class",
  "events" = "/dashboard/events",
  "add-event" = "/dashboard/events/add-event",
  "class-details" = "/dashboard/schedule/details",
  home = "/dashboard",
  pricing = "/dashboard/pricing",
  profile = "/dashboard/profile",
  login = "/auth/login",
  register = "/auth/signup",
  reviews = "/dashboard/reviews",
  account = "/dashboard/account",
  attendance = "/dashboard/attendance",
  message = "/dashboard/message",
}
